### ISSUE TITLE
Adjusting the "V" value affects "S"

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/react-colorpickr#29]
![color-picker-1](https://cloud.githubusercontent.com/assets/5607844/9124614/73f748f4-3c66-11e5-8f16-fa143892861c.gif)

/cc @tristen

**Comment by kelvinabrokwa** [comment]
I can't quite figure out why/when this happens but it also happens with `S`

![cp](https://cloud.githubusercontent.com/assets/7795202/9185678/dba0239a-3f8b-11e5-9614-5eedef856617.gif)

**Comment by tmcw** [comment]
@scothis is working out the kinks in colorpicker - the root problem is likely that it's only keeping track of colors, not input values, internally, and so if a color loses a component, like red turning to black and losing hue, it is reflected in the ui.

**Comment by kelvinabrokwa** [comment]
@tmcw ah good to know, I was just about to start poking around in here myself but if @scothis is on it then bueno :+1:

**Comment by mcwhittemore** [comment]
@tmcw So the root of the problem here is that the value that sets state is RGBA which has to be converted to HSV.

In the conversion process we round which creates the above gifs. To solve this we can either save all the input values in the state and read from those after the component is loaded, or we can report a css value to onChange that will be translated correctly.

The onChange method seems best as it should fix this problem both while the component is being edited and when the component is loaded. That said, HSV isn't a valid CSS color. We could use HSLA, but I'm not sure what the reasons for using HSV vs HSL were.

**Comment by tristen** [comment]
> The onChange method seems best as it should fix this problem both while the component is being edited and when the component is loaded.

:+1: 

>  We could use HSLA, but I'm not sure what the reasons for using HSV vs HSL were.

No strong reasons here. We should use HSLA

**Comment by tmcw** [comment]
Design-wise we shouldn't require that the color input mirrors any CSS color format - we may support [perceptual color spaces](https://en.wikipedia.org/wiki/Lab_color_space) relatively soon because of their popularity in mapmaking.

**Comment by nickidlugash** [comment]
This seems fixed via https://github.com/mapbox/react-colorpickr/pull/32. @tmcw @tristen @mcwhittemore can we close this issue, or are do you want to continue your conversation here?

**Comment by tristen** [comment]
Capturing https://github.com/mapbox/react-colorpickr/issues/29#issuecomment-129954682 in https://github.com/mapbox/react-colorpickr/issues/33. We can close this out.
