### ISSUE TITLE
Provide ES5 version

### ISSUE THREAD

**Issue by khakulov** [mapbox/react-colorpickr#37]
Is it possible to provide ES5 version for use in browser without transpiling?

**Comment by tmcw** [comment]
It's not in the works right now - we'd accept a PR, but react-colorpickr is designed to be used with either browserify or webpack, both of which work well with transpiling and are relatively ubiquitous in the React ecosystem.

**Comment by idolize** [comment]
@tmcw browserify and webpack don't (by themselves) handle ES6 -> ES5 transpilation. Typically a tool like [babel](http://babeljs.io) is used for that.

Also, typically library authors do the babel transpilation _before_ publishing to npm (as part of a build script or `prepublish` hook, for example), because it is expensive and unnecessary for every developer _using_ third party libraries to always transpile everything in `node_modules` on every build, when really the libraries only need to be rebuilt each time they are updated.
